version: "3"

services:
  pull-pid-platform:
    build: .
    image: http-rest-srv
    container_name: http-rest-srv
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"

networks:
  default:
    external:
       name: influxdb-net
