version: "3"

services:
  pid-stability-check:
    build: .
    image: pid-stability-check
    container_name: pid-stability-check
    restart: always

networks:
  default:
    external:
       name: influx-net
