version: "3"

services:
  pull-pid-platform:
    build: .
    image: pull-pid-platform
    container_name: pull-pid-platform
    restart: always

networks:
  default:
    external:
       name: influx-net
